# Generated by Django 3.1 on 2021-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211016_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
